INSERT INTO SEX (SEX) VALUES ('Male');
INSERT INTO SEX (SEX) VALUES ('Female');
INSERT INTO PERSON (NAME, SEX_ID) VALUES ('Dorota',1);
INSERT INTO PERSON (NAME, SEX_ID) VALUES ('Krzysiek',2);
INSERT INTO PERSON_TO_PERSON(PERSON_ID1, PERSON_ID2) VALUES (1,2)