DROP TABLE IF EXISTS SEX;
CREATE TABLE SEX
(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	SEX VARCHAR(20),
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON
(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),
	SEX_ID INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (SEX_ID) REFERENCES SEX(ID)
);

DROP TABLE IF EXISTS PERSON_TO_PERSON;
CREATE TABLE PERSON_TO_PERSON
(
	PERSON_ID1 INTEGER,
	PERSON_ID2 INTEGER,
	FOREIGN KEY (PERSON_ID1) REFERENCES PERSON(ID),
	FOREIGN KEY (PERSON_ID2) REFERENCES PERSON(ID)
);