DROP TABLE IF EXISTS SEX;
CREATE TABLE SEX
(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
SEX VARCHAR(20)
);

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON
(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
SEX_ID INTEGER,
FOREIGN KEY (SEX_ID) REFERENCES SEX(ID)
);